# This is a basic workflow to help you get started with Actions

name: Build-On-Windows-2019

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildCooolis:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.4.1
    
    - name: Compile x86 Program
      working-directory: ./
      run: msbuild /p:configuration=release /p:platform=x86 SchtaskCreator.vcxproj

    - name: pack x86 zip
      working-directory: ./
      shell: powershell
      run: Compress-Archive -Path "Release\SchtaskCreator.exe" -DestinationPath "C:\SchtaskCreatorX86.zip"
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: SchtaskCreator Release ${{ github.ref }}
        body: |
          Automated Release by GitHub Action CI
        draft: false
        prerelease: false
    - name: Upload Release Asset (x86)
      id: upload-release-asset-x86
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C:\SchtaskCreatorX86.zip
        asset_name: SchtaskCreatorX86.zip
        asset_content_type: application/zip
